# Generated by Django 2.1 on 2020-03-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCarApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesseeprofile',
            name='driving_license',
            field=models.ImageField(blank=True, upload_to='driving_licenses'),
        ),
    ]
