# Generated by Django 2.1 on 2020-03-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCarApp', '0002_auto_20200312_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesseeprofile',
            name='lessee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lessorprofile',
            name='lessor',
            field=models.BooleanField(default=True),
        ),
    ]
