# Generated by Django 2.1 on 2020-03-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCarApp', '0003_auto_20200312_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesseeprofile',
            old_name='lessee',
            new_name='userType',
        ),
        migrations.RemoveField(
            model_name='lessorprofile',
            name='lessor',
        ),
        migrations.AddField(
            model_name='lessorprofile',
            name='userType',
            field=models.BooleanField(default=False),
        ),
    ]
