# Generated by Django 2.1 on 2020-03-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCarApp', '0005_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesseeprofile',
            old_name='user',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='lessorprofile',
            old_name='user',
            new_name='User',
        ),
    ]
