# Generated by Django 2.1 on 2020-03-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCarApp', '0007_auto_20200312_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesseeprofile',
            name='userType',
        ),
        migrations.RemoveField(
            model_name='lessorprofile',
            name='userType',
        ),
    ]
