# Generated by Django 2.1 on 2020-03-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCarApp', '0008_auto_20200312_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=10)),
                ('transmission', models.CharField(max_length=10)),
                ('fuel_type', models.CharField(max_length=10)),
                ('first_available_day', models.DateField()),
                ('last_available_day', models.DateField()),
                ('price_per_day', models.FloatField()),
            ],
        ),
    ]
