# Generated by Django 2.1 on 2020-03-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCarApp', '0011_auto_20200313_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='CC',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(upload_to='car_photos'),
        ),
    ]
