# Generated by Django 2.1 on 2020-03-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCarApp', '0012_auto_20200313_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.FileField(upload_to='car_photos'),
        ),
    ]
