# Generated by Django 2.1 on 2020-03-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCarApp', '0013_auto_20200319_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.FileField(blank=True, upload_to='car_photos'),
        ),
    ]
