# Generated by Django 2.1 on 2020-03-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCarApp', '0016_auto_20200319_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto')], max_length=10),
        ),
    ]
