# Generated by Django 2.1 on 2020-03-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCarApp', '0017_auto_20200319_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuelType',
            field=models.CharField(choices=[('GASOLINE', 'Gasoline'), ('DIESEL', 'Diesel'), ('GAS', 'Gas'), ('ELECTRIC', 'Electric')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, upload_to='car_photos'),
        ),
    ]
