# Generated by Django 2.1 on 2020-09-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCarApp', '0020_auto_20200917_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesseeprofile',
            name='cars_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
