# Generated by Django 2.1 on 2020-09-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCarApp', '0023_auto_20200925_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='averageCcGap',
        ),
    ]
